/*
 * Copyright Maner·Fan
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Claude 暖调风格 Light 主题配置
export const shadcnLightToken = {
    fontFamily: "var(--font-body)",
    fontFamilyCode: "var(--font-mono)",
    colorPrimary: '#3d3d3a',
    colorSuccess: '#3f7a3a',
    colorWarning: '#c96442',
    colorError: '#b53333',
    colorInfo: '#3d3d3a',
    colorTextBase: '#141413',
    colorBgBase: '#faf9f5',
    colorPrimaryBg: '#e8e6dc',
    colorPrimaryBgHover: '#d1cfc5',
    colorPrimaryBorder: '#e8e6dc',
    colorPrimaryBorderHover: '#d1cfc5',
    colorPrimaryHover: '#4d4c48',
    colorPrimaryActive: '#141413',
    colorPrimaryText: '#141413',
    colorPrimaryTextHover: '#4d4c48',
    colorPrimaryTextActive: '#141413',
    colorSuccessBg: '#f0f5ee',
    colorSuccessBgHover: '#dde9d8',
    colorSuccessBorder: '#c2d9b8',
    colorSuccessBorderHover: '#a3c794',
    colorSuccessHover: '#357030',
    colorSuccessActive: '#2d5f28',
    colorSuccessText: '#3f7a3a',
    colorSuccessTextHover: '#3f7a3a',
    colorSuccessTextActive: '#357030',
    colorWarningBg: '#fdf5f0',
    colorWarningBgHover: '#f8e4d6',
    colorWarningBorder: '#f0c8b0',
    colorWarningBorderHover: '#e0a882',
    colorWarningHover: '#b5563a',
    colorWarningActive: '#9e4830',
    colorWarningText: '#c96442',
    colorWarningTextHover: '#c96442',
    colorWarningTextActive: '#b5563a',
    colorErrorBg: '#faf0f0',
    colorErrorBgHover: '#f5dddd',
    colorErrorBorder: '#e8b8b8',
    colorErrorBorderHover: '#d89898',
    colorErrorHover: '#a02c2c',
    colorErrorActive: '#882424',
    colorErrorText: '#b53333',
    colorErrorTextHover: '#b53333',
    colorErrorTextActive: '#a02c2c',
    colorInfoBg: '#e8e6dc',
    colorInfoBgHover: '#d1cfc5',
    colorInfoBorder: '#d1cfc5',
    colorInfoBorderHover: '#b0aea5',
    colorInfoHover: '#4d4c48',
    colorInfoActive: '#141413',
    colorInfoText: '#141413',
    colorInfoTextHover: '#4d4c48',
    colorInfoTextActive: '#141413',
    colorText: '#141413',
    colorTextSecondary: '#4d4c48',
    colorTextTertiary: '#87867f',
    colorTextQuaternary: '#b0aea5',
    colorTextDisabled: '#b0aea5',
    colorBgContainer: '#faf9f5',
    colorBgElevated: '#ffffff',
    colorBgLayout: '#f5f4ed',
    colorBgSpotlight: '#3d3d3a',
    colorBgMask: 'rgba(20, 20, 19, 0.45)',
    colorBorder: '#f0eee6',
    colorBorderSecondary: '#f0eee6',
    borderRadius: 10,
    borderRadiusXS: 2,
    borderRadiusSM: 8,
    borderRadiusLG: 14,
    padding: 16,
    paddingSM: 12,
    paddingLG: 24,
    margin: 16,
    marginSM: 12,
    marginLG: 24,
    boxShadow: 'rgba(0,0,0,0.05) 0px 4px 24px',
    boxShadowSecondary: 'rgba(0,0,0,0.08) 0px 4px 12px',
}

// Claude 暖调风格 Dark 主题配置
export const shadcnDarkToken = {
    fontFamily: "var(--font-body)",
    fontFamilyCode: "var(--font-mono)",
    colorPrimary: '#faf9f5',
    colorSuccess: '#4ade80',
    colorWarning: '#f97316',
    colorError: '#ef4444',
    colorInfo: '#faf9f5',
    colorTextBase: '#faf9f5',
    colorBgBase: '#141413',
    colorPrimaryBg: '#30302e',
    colorPrimaryBgHover: '#3d3d3a',
    colorPrimaryBorder: '#30302e',
    colorPrimaryBorderHover: '#3d3d3a',
    colorPrimaryHover: '#e4e2d8',
    colorPrimaryActive: '#faf9f5',
    colorPrimaryText: '#141413',
    colorPrimaryTextHover: '#141413',
    colorPrimaryTextActive: '#141413',
    colorSuccessBg: '#0f2d1a',
    colorSuccessBgHover: '#1a4028',
    colorSuccessBorder: '#1a4028',
    colorSuccessBorderHover: '#4ade80',
    colorSuccessHover: '#3fcc70',
    colorSuccessActive: '#4ade80',
    colorSuccessText: '#4ade80',
    colorSuccessTextHover: '#4ade80',
    colorSuccessTextActive: '#6ee7a0',
    colorWarningBg: '#3a1c08',
    colorWarningBgHover: '#5a2e10',
    colorWarningBorder: '#5a2e10',
    colorWarningBorderHover: '#f97316',
    colorWarningHover: '#ea6c10',
    colorWarningActive: '#f97316',
    colorWarningText: '#f97316',
    colorWarningTextHover: '#f97316',
    colorWarningTextActive: '#fdba74',
    colorErrorBg: '#3a1010',
    colorErrorBgHover: '#5a1818',
    colorErrorBorder: '#5a1818',
    colorErrorBorderHover: '#ef4444',
    colorErrorHover: '#dc3636',
    colorErrorActive: '#ef4444',
    colorErrorText: '#ef4444',
    colorErrorTextHover: '#ef4444',
    colorErrorTextActive: '#fca5a5',
    colorInfoBg: '#30302e',
    colorInfoBgHover: '#3d3d3a',
    colorInfoBorder: '#30302e',
    colorInfoBorderHover: '#3d3d3a',
    colorInfoHover: '#e4e2d8',
    colorInfoActive: '#faf9f5',
    colorInfoText: '#faf9f5',
    colorInfoTextHover: '#e4e2d8',
    colorInfoTextActive: '#faf9f5',
    colorText: '#faf9f5',
    colorTextSecondary: '#d1cfc5',
    colorTextTertiary: '#87867f',
    colorTextQuaternary: '#5e5d59',
    colorTextDisabled: '#5e5d59',
    colorBgContainer: '#1a1a18',
    colorBgElevated: '#232320',
    colorBgLayout: '#141413',
    colorBgSpotlight: '#faf9f5',
    colorTextLightSolid: '#141413',
    colorBgMask: 'rgba(0, 0, 0, 0.65)',
    colorBorder: '#30302e',
    colorBorderSecondary: '#1e1e1c',
    borderRadius: 10,
    borderRadiusXS: 2,
    borderRadiusSM: 8,
    borderRadiusLG: 14,
    padding: 16,
    paddingSM: 12,
    paddingLG: 24,
    margin: 16,
    marginSM: 12,
    marginLG: 24,
    boxShadow: 'rgba(0,0,0,0.3) 0px 4px 24px',
    boxShadowSecondary: 'rgba(0,0,0,0.4) 0px 4px 12px',
}
