/*
 * Copyright Maner·Fan
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Shadcn 风格 Light 主题配置
export const shadcnLightToken = {
    fontFamily: "var(--font-body)",
    fontFamilyCode: "var(--font-mono)",
    colorPrimary: '#18181b',
    colorSuccess: '#22c55e',
    colorWarning: '#f97316',
    colorError: '#ef4444',
    colorInfo: '#18181b',
    colorTextBase: '#18181b',
    colorBgBase: '#ffffff',
    colorPrimaryBg: '#f4f4f5',
    colorPrimaryBgHover: '#e4e4e7',
    colorPrimaryBorder: '#d4d4d8',
    colorPrimaryBorderHover: '#a1a1aa',
    colorPrimaryHover: '#27272a',
    colorPrimaryActive: '#09090b',
    colorPrimaryText: '#18181b',
    colorPrimaryTextHover: '#27272a',
    colorPrimaryTextActive: '#09090b',
    colorSuccessBg: '#f0fdf4',
    colorSuccessBgHover: '#dcfce7',
    colorSuccessBorder: '#bbf7d0',
    colorSuccessBorderHover: '#86efac',
    colorSuccessHover: '#16a34a',
    colorSuccessActive: '#15803d',
    colorSuccessText: '#16a34a',
    colorSuccessTextHover: '#16a34a',
    colorSuccessTextActive: '#15803d',
    colorWarningBg: '#fff7ed',
    colorWarningBgHover: '#fed7aa',
    colorWarningBorder: '#fdba74',
    colorWarningBorderHover: '#fb923c',
    colorWarningHover: '#ea580c',
    colorWarningActive: '#c2410c',
    colorWarningText: '#ea580c',
    colorWarningTextHover: '#ea580c',
    colorWarningTextActive: '#c2410c',
    colorErrorBg: '#fef2f2',
    colorErrorBgHover: '#fecaca',
    colorErrorBorder: '#fca5a5',
    colorErrorBorderHover: '#f87171',
    colorErrorHover: '#dc2626',
    colorErrorActive: '#b91c1c',
    colorErrorText: '#dc2626',
    colorErrorTextHover: '#dc2626',
    colorErrorTextActive: '#b91c1c',
    colorInfoBg: '#f4f4f5',
    colorInfoBgHover: '#e4e4e7',
    colorInfoBorder: '#d4d4d8',
    colorInfoBorderHover: '#a1a1aa',
    colorInfoHover: '#27272a',
    colorInfoActive: '#09090b',
    colorInfoText: '#18181b',
    colorInfoTextHover: '#27272a',
    colorInfoTextActive: '#09090b',
    colorText: '#18181b',
    colorTextSecondary: '#3f3f46',
    colorTextTertiary: '#71717a',
    colorTextQuaternary: '#a1a1aa',
    colorTextDisabled: '#a1a1aa',
    colorBgContainer: '#ffffff',
    colorBgElevated: '#ffffff',
    colorBgLayout: '#fafafa',
    colorBgSpotlight: '#18181b',
    colorBgMask: 'rgba(24, 24, 27, 0.45)',
    colorBorder: '#e4e4e7',
    colorBorderSecondary: '#f4f4f5',
    borderRadius: 10,
    borderRadiusXS: 2,
    borderRadiusSM: 6,
    borderRadiusLG: 14,
    padding: 16,
    paddingSM: 12,
    paddingLG: 24,
    margin: 16,
    marginSM: 12,
    marginLG: 24,
    boxShadow: '0 1px 3px 0 rgba(0, 0, 0, 0.1), 0 1px 2px -1px rgba(0, 0, 0, 0.1)',
    boxShadowSecondary: '0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -2px rgba(0, 0, 0, 0.1)',
}

// Shadcn 风格 Dark 主题配置
export const shadcnDarkToken = {
    fontFamily: "var(--font-body)",
    fontFamilyCode: "var(--font-mono)",
    colorPrimary: '#fafafa',
    colorSuccess: '#22c55e',
    colorWarning: '#f97316',
    colorError: '#ef4444',
    colorInfo: '#fafafa',
    colorTextBase: '#fafafa',
    colorBgBase: '#09090b',
    colorPrimaryBg: '#27272a',
    colorPrimaryBgHover: '#3f3f46',
    colorPrimaryBorder: '#3f3f46',
    colorPrimaryBorderHover: '#52525b',
    colorPrimaryHover: '#e4e4e7',
    colorPrimaryActive: '#ffffff',
    // Primary 按钮背景是浅色，所以文字应该是深色
    colorPrimaryText: '#18181b',
    colorPrimaryTextHover: '#18181b',
    colorPrimaryTextActive: '#18181b',
    colorSuccessBg: '#052e16',
    colorSuccessBgHover: '#166534',
    colorSuccessBorder: '#166534',
    colorSuccessBorderHover: '#22c55e',
    colorSuccessHover: '#16a34a',
    colorSuccessActive: '#22c55e',
    colorSuccessText: '#22c55e',
    colorSuccessTextHover: '#22c55e',
    colorSuccessTextActive: '#4ade80',
    colorWarningBg: '#431407',
    colorWarningBgHover: '#7c2d12',
    colorWarningBorder: '#7c2d12',
    colorWarningBorderHover: '#f97316',
    colorWarningHover: '#ea580c',
    colorWarningActive: '#f97316',
    colorWarningText: '#f97316',
    colorWarningTextHover: '#f97316',
    colorWarningTextActive: '#fdba74',
    colorErrorBg: '#450a0a',
    colorErrorBgHover: '#7f1d1d',
    colorErrorBorder: '#7f1d1d',
    colorErrorBorderHover: '#ef4444',
    colorErrorHover: '#dc2626',
    colorErrorActive: '#ef4444',
    colorErrorText: '#ef4444',
    colorErrorTextHover: '#ef4444',
    colorErrorTextActive: '#fca5a5',
    colorInfoBg: '#27272a',
    colorInfoBgHover: '#3f3f46',
    colorInfoBorder: '#3f3f46',
    colorInfoBorderHover: '#52525b',
    colorInfoHover: '#e4e4e7',
    colorInfoActive: '#ffffff',
    colorInfoText: '#fafafa',
    colorInfoTextHover: '#e4e4e7',
    colorInfoTextActive: '#ffffff',
    colorText: '#fafafa',
    colorTextSecondary: '#d4d4d8',
    colorTextTertiary: '#a1a1aa',
    colorTextQuaternary: '#71717a',
    colorTextDisabled: '#52525b',
    colorBgContainer: '#18181b',
    colorBgElevated: '#27272a',
    colorBgLayout: '#09090b',
    colorBgSpotlight: '#fafafa',
    colorTextLightSolid: '#18181b',
    colorBgMask: 'rgba(0, 0, 0, 0.65)',
    colorBorder: '#27272a',
    colorBorderSecondary: '#18181b',
    borderRadius: 10,
    borderRadiusXS: 2,
    borderRadiusSM: 6,
    borderRadiusLG: 14,
    padding: 16,
    paddingSM: 12,
    paddingLG: 24,
    margin: 16,
    marginSM: 12,
    marginLG: 24,
    boxShadow: '0 1px 3px 0 rgba(0, 0, 0, 0.3), 0 1px 2px -1px rgba(0, 0, 0, 0.3)',
    boxShadowSecondary: '0 4px 6px -1px rgba(0, 0, 0, 0.3), 0 2px 4px -2px rgba(0, 0, 0, 0.3)',
}
